title: ADDCON Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.addcon.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - category: Uncategorized
      name: addcon.com website
    - name: File server
      category: Corporate Network
      description: Within corporate network
    - name: Citrix & Navision
      category: Corporate Network
      description: Within corporate network
    - name: Printing & Scanning
      category: Corporate Network
      description: Within corporate network
    - name: Internet access
      category: Corporate Network
      description: Access to the internet from inside the corporate network
    - name: Clue
      category: Norway specific
    - name: Synergi
      category: Norway specific
    - name: Emmasped
      category: Norway specific
    - name: IBM Lotus Notes
      category: Corporate Network
    - name: BarTender
      category: Germany specific
      description: Shipping label printing
    - name: SFirm
      category: Germany Specific
      description: Corporate banking
    - name: Kelio Bodet
      category: Germany specific
      description: Time & Attendance
    - name: Vodafone Telephony
      category: Germany specific
      description: Landline and Mobile telephony in Germany
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#f57920"
  enableLastMod: false
  headerTextColor: white
  logo: https://addcon.com/images/addcon/logo/addcon.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
    - name: Corporate Network
      description: Services available only while at Bitterfeld, Porsgrunn or via VPN
      closed: false
    - name: Germany specific
      description: Services specific to German users
      closed: true
    - name: Norway specific
      description: Services specific to Norwegian users
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: false
